version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=workout_user
      - DB_PASSWORD=workout_password
      - DB_NAME=workout_db
      - PORT=8000
      - ENV=development

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=workout_db
      - MYSQL_USER=workout_user
      - MYSQL_PASSWORD=workout_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: