apiVersion: v1
kind: Secret
metadata:
  name: workout-db-secrets
type: Opaque
data:
  # These are base64 encoded values
  # echo -n "root_password" | base64
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  # echo -n "workout_user" | base64
  MYSQL_USER: d29ya291dF91c2Vy
  # echo -n "workout_password" | base64
  MYSQL_PASSWORD: d29ya291dF9wYXNzd29yZA==